[package]
org = "atheeque"
name = "Finance_MIS"
version = "0.1.0"
distribution = "2201.8.6"

[build-options]
observabilityIncluded = true

[dependencies]
"ballerinax/googleapis.bigquery" = "1.2.0"
"ballerinax/googleapis.bigquery.datatransfer" = "0.1.0"